import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Madryn Buceo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{children: React.ReactNode }>) {
  return (
    <html lang="es">
      <body className={inter.className + "container mx-auto font-semibold"}>
        <Header />
        {children}
      </body>
    </html>
  );
}
